server:
  port: 8848
aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4GDpBsdKA81x2Uj99dV8
  accessKeySecret: LPANalMr0nW3KIbAZzuww21dUDYAhs
  bucketName: lixin62
  urlPrefix: lixin62.oss-cn-beijing.aliyuncs.com
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  application:
    name: lxoss
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8861/eureka